# LightGBMのパラメータ設定ファイル
# boosting_type: ブースティングタイプを指定 ('gbdt' は勾配ブースティング決定木)
boosting_type: 'gbdt'

# num_leaves: 1つのツリーにおける葉の最大数
num_leaves: 16

# learning_rate: 学習率
learning_rate: 0.1

# n_estimators: ブースティングラウンドの数
n_estimators: 100000

# min_gain_to_split: 分割に必要な最小ゲイン
min_gain_to_split: 0.5

# objective: 最適化する目的関数
objective: 'binary'

# metric: 評価指標
metric: 'auc'

# random_state: 結果の再現性を保証するための乱数シード
random_state: 0