# randam forest parameters
random_forest_config:
  n_estimators: [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]
  max_depth: [3, 4, 5, 6, 7, 8, 9]
  random_state: 10
  max_features: 'sqrt'


# select columns
column_settings:
  train_columns: ['Survived', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked', 'TicketGroup', 'Honorifics', 'FamilySize', 'FamilyLabel']
  test_columns: ['Age', 'SibSp', 'Parch', 'Fare', 'Embarked', 'TicketGroup', 'Honorifics', 'FamilySize', 'FamilyLabel']
